import Head from 'next/head';
import { Fragment } from 'react';
import { BsArrowLeft, BsArrowRight } from 'react-icons/bs';
import Slider, { Settings } from 'react-slick';

import { Hero } from '@/components';
import MainLayout from '@/layouts/MainLayout/MainLayout';

import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  const sliderSettings: Settings = {
    dots: false,
    arrows: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    fade: true,
    nextArrow: <BsArrowRight />,
    prevArrow: <BsArrowLeft />,
  };
  return (
    <Fragment>
      <Head>
        <title>Unisex fashion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider {...sliderSettings}>
        <Hero
          backgroundUrl="/hero-1.jpg"
          title="Fall - Winter Collections 2030"
          shortTitle="Summer Collection"
          description="A specialist label creating luxury essentials. Ethically crafted with an unwavering
commitment to exceptional quality."
        />
        <Hero
          backgroundUrl="/hero-2.jpg"
          title="Fall - Winter Collections 2030"
          shortTitle="Summer Collection"
          description="A specialist label creating luxury essentials. Ethically crafted with an unwavering
commitment to exceptional quality."
        />
      </Slider>
    </Fragment>
  );
};

export default Home;

Home.getLayout = (page) => <MainLayout>{page}</MainLayout>;
