import Head from 'next/head';
import { Fragment } from 'react';

import MainLayout from '@/layouts/MainLayout/MainLayout';

import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="bg-blue-200">Home page</h1>
    </Fragment>
  );
};

export default Home;

Home.getLayout = (page) => <MainLayout>{page}</MainLayout>;
